# Generated by Django 4.0.5 on 2022-06-30 01:00

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import sorl.thumbnail.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(max_length=500, verbose_name='slug')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('website', models.URLField(max_length=255, verbose_name='website')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='phone')),
                ('overview', tinymce.models.HTMLField(blank=True, null=True, verbose_name='overview')),
                ('logo', sorl.thumbnail.fields.ImageField(upload_to='company/logos/', verbose_name='logo')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='verfied status')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
            },
        ),
    ]
